---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tahakomp1/public_html/pdf_pro/
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH && composer install --no-dev --optimize-autoloader
    - cd $DEPLOYPATH && php artisan config:cache
    - cd $DEPLOYPATH && php artisan route:cache
    - cd $DEPLOYPATH && php artisan view:cache
